# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36d77615c5aaffbffb8b6f0daf450d461924c9431922976ca67bdb7cc66b187c7e2db46a53d9f2479fd3ed54a0988da0c126aa197601835969be0a8a1518aad5

test:
  secret_key_base: 1c1c6513e001f2c2160e2c8146b7fa46a7ffd14e42578afa42a1da76970f081278114536f135127c3145461c392aadd519c75fbc5780346b37f937cccc8e5fd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
